version: '3.8'
services: 
  ji-ex:
    build: 
      context:  .
      dockerfile: Dockerfile
    container_name: ji-ex
    command: sh -c "yarn dev"
    ports: 
      - 3000:3000
      volumes:
      - .:/ji-ex
      - /ji-ex/node_modules

      