version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  node:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/ji-ex
      - /ji-ex/node_modules
